### PR TITLE
fix: default secret and config UID/GID to "0" to prevent parsing errors

### LINKED ISSUE #2421: 🐞 Bug: Secrets are unusable in Swarm mode
### Bug Description

When trying to use swarm secrets, the stack fails to update. 

I can create a secret in the UI and in the swarm, but using it in a stack definition fails the stack update with the following error:

`starting container failed: strconv.Atoi: parsing "": invalid syntax`

using `docker inspect` shows the task failed 

`update paused due to failure or early termination of task xxxxxxxxxxx` 

### Steps To Reproduce

1. Create a Swarm secret
2. Mount that secret in a stack definition

```yaml
secrets:
  secret_name:
    external: true 
```

3. Save the stack definition

### Expected Behavior

Containers deploy correctly, with the secret available in the container as `/run/secret/<secret_name>`

### Actual Behavior

The container deployment fails with the above error

### Screenshots

_No response_

### Arcane Version

v1.18.0

### Installation Method

Docker Compose (Recommended)

### Environment Type

Local Docker (Single instance)

### Database Type

SQLite (Default)

### Operating System

Linux

### Docker Version

29.4.0

### Browser & Version

_No response_

### Relevant Logs or Error Messages

```shell

```

### Docker Compose Configuration

```yaml

```

### Environment Configuration (.env file)

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SplinterHead**
## Checklist

- [x] This PR is **not** opened from my fork’s `main` branch

## What This PR Implements

This PR resolves a container startup failure (`strconv.Atoi: parsing "": invalid syntax`) that occurs when deploying Docker Swarm services with secrets or configs that lack explicit UID/GID definitions. The fix ensures that these fields default to `"0"` (root) rather than an empty string, maintaining compatibility with the Docker Swarm API and internal daemon parsing logic.

## Related Issue
Fixes #2421 

## Changes Made

- **Stack Deployment Engine**: Updated `backend/pkg/libarcane/swarm/stack_deploy_engine.go` to ensure `UID` and `GID` default to `"0"` during the conversion from Compose types to Swarm API types.
- **Swarm Service**: Updated `backend/internal/services/swarm_service.go` to include a `sanitizeServiceSpecInternal` helper. This ensures that services created or updated directly through the Arcane UI also benefit from the same numeric defaults for secret and config references.
- **Helper Utility**: Introduced `stringOrDefaultInternal` in the stack engine to handle empty or whitespace-only string sanitization safely.

## Testing Done

- [x] Development environment started: `./scripts/development/dev.sh start`
- [x] Frontend verified at http://localhost:3000
- [x] Backend verified at http://localhost:3552
- [x] Manual testing completed (describe):
  - Create a Secret via the UI
  - Deploy a Docker stack that utilises that secret
  - Use the shell to verify the secret file content in `/run/secret/` 
- [x] No linting errors (e.g., `just lint all`)
- [x] Backend tests pass: `just test backend`

## AI Tool Used (if applicable)

Antigravity (Advanced Agentic Coding)

AI Tool:
Assistance Level: Significant
What AI helped with: coding and commit message
I reviewed and edited all AI-generated output: yes
I ran all required tests and manually verified changes: yes

**Disclaimer** Greptiles Reviews use AI, make sure to check over its work.

To better help train Greptile on our codebase, if the comment is useful and valid **Like** the comment, if its not helpful or invalid **Dislike**

To have Greptile Re-Review the changes, mention `greptileai`.

<details open><summary><h3>Greptile Summary</h3></summary>

This PR fixes a Docker Swarm service startup failure (`strconv.Atoi: parsing "": invalid syntax`) by defaulting empty `UID`/`GID` fields in secret and config references to `"0"` (root). The fix is applied in two places: the stack deploy engine (compose-to-swarm conversion) and the swarm service's create/update paths via a new `sanitizeServiceSpecInternal` helper. The logic is correct — mutations through the `File` pointer field in the range loops are effective.
</details>

<details open><summary><h3>Confidence Score: 5/5</h3></summary>

Safe to merge — the fix is correct, targeted, and addresses a real production crash with no regressions introduced.

The only finding is a P2 defensive nil-guard suggestion on individual slice elements, which is not a present defect since Docker's SDK does not produce nil refs in these slices under normal operation.

No files require special attention.
</details>

<a href="https://chatgpt.com/codex/deeplink?prompt=IMPORTANT%3A%20Work%20in%20the%20repository%20%22getarcaneapp%2Farcane%22%20on%20the%20existing%20branch%20%22fix%2Fdocker-swarm-secrets%22.%20Checkout%20that%20branch%20%E2%80%94%20do%20NOT%20create%20a%20new%20branch%20or%20open%20a%20new%20PR.%20Push%20your%20changes%20to%20%22fix%2Fdocker-swarm-secrets%22.%0A%0AFix%20the%20following%201%20code%20review%20issues.%20Work%20through%20them%20one%20at%20a%20time%2C%20proposing%20concise%20fixes.%0A%0A---%0A%0A%23%23%23%20Issue%201%20of%201%0Abackend%2Finternal%2Fservices%2Fswarm_service.go%3A2396-2415%0A**Missing%20nil%20guard%20on%20individual%20refs**%0A%0ABoth%20loops%20dereference%20%60ref.File%60%20without%20first%20checking%20%60ref%20!%3D%20nil%60.%20Since%20%60Secrets%60%20and%20%60Configs%60%20are%20%60%5B%5D*swarm.SecretReference%60%20%2F%20%60%5B%5D*swarm.ConfigReference%60%20%28pointer%20slices%29%2C%20a%20%60nil%60%20element%20in%20either%20slice%20would%20panic%20before%20the%20%60ref.File%20!%3D%20nil%60%20check%20is%20reached.%20While%20Docker's%20own%20plumbing%20rarely%20produces%20nil%20elements%2C%20a%20defensive%20guard%20keeps%20the%20helper%20resilient%20to%20callers%20or%20mocks%20that%20don't%20guarantee%20non-nil%20entries.%0A%0A%60%60%60suggestion%0A%09for%20_%2C%20ref%20%3A%3D%20range%20spec.TaskTemplate.ContainerSpec.Secrets%20%7B%0A%09%09if%20ref%20!%3D%20nil%20%26%26%20ref.File%20!%3D%20nil%20%7B%0A%09%09%09if%20strings.TrimSpace%28ref.File.UID%29%20%3D%3D%20%22%22%20%7B%0A%09%09%09%09ref.File.UID%20%3D%20%220%22%0A%09%09%09%7D%0A%09%09%09if%20strings.TrimSpace%28ref.File.GID%29%20%3D%3D%20%22%22%20%7B%0A%09%09%09%09ref.File.GID%20%3D%20%220%22%0A%09%09%09%7D%0A%09%09%7D%0A%09%7D%0A%0A%09for%20_%2C%20ref%20%3A%3D%20range%20spec.TaskTemplate.ContainerSpec.Configs%20%7B%0A%09%09if%20ref%20!%3D%20nil%20%26%26%20ref.File%20!%3D%20nil%20%7B%0A%09%09%09if%20strings.TrimSpace%28ref.File.UID%29%20%3D%3D%20%22%22%20%7B%0A%09%09%09%09ref.File.UID%20%3D%20%220%22%0A%09%09%09%7D%0A%09%09%09if%20strings.TrimSpace%28ref.File.GID%29%20%3D%3D%20%22%22%20%7B%0A%09%09%09%09ref.File.GID%20%3D%20%220%22%0A%09%09%09%7D%0A%09%09%7D%0A%09%7D%0A%60%60%60%0A%0A"><picture><source media="(prefers-color-scheme: dark)" srcset="https://greptile-static-assets.s3.amazonaws.com/badges/FixAllInCodexDark.svg?v=2"><source media="(prefers-color-scheme: light)" srcset="https://greptile-static-assets.s3.amazonaws.com/badges/FixAllInCodex.svg?v=2">Fix All in Codex</picture></a>

<details><summary>Prompt To Fix All With AI</summary>

`````markdown
This is a comment left during a code review.
Path: backend/internal/services/swarm_service.go
Line: 2396-2415

Comment:
**Missing nil guard on individual refs**

Both loops dereference `ref.File` without first checking `ref != nil`. Since `Secrets` and `Configs` are `[]*swarm.SecretReference` / `[]*swarm.ConfigReference` (pointer slices), a `nil` element in either slice would panic before the `ref.File != nil` check is reached. While Docker's own plumbing rarely produces nil elements, a defensive guard keeps the helper resilient to callers or mocks that don't guarantee non-nil entries.

```suggestion
	for _, ref := range spec.TaskTemplate.ContainerSpec.Secrets {
		if ref != nil && ref.File != nil {
			if strings.TrimSpace(ref.File.UID) == "" {
				ref.File.UID = "0"
			}
			if strings.TrimSpace(ref.File.GID) == "" {
				ref.File.GID = "0"
			}
		}
	}

	for _, ref := range spec.TaskTemplate.ContainerSpec.Configs {
		if ref != nil && ref.File != nil {
			if strings.TrimSpace(ref.File.UID) == "" {
				ref.File.UID = "0"
			}
			if strings.TrimSpace(ref.File.GID) == "" {
				ref.File.GID = "0"
			}
		}
	}
```

How can I resolve this? If you propose a fix, please make it concise.
`````

</details>

<sub>Reviews (1): Last reviewed commit: ["fix: default secret and config UID/GID t..."](https://github.com/getarcaneapp/arcane/commit/a6ccb8dc1a6550686c8580d5df85cbb48ce8f342) | [Re-trigger Greptile](https://app.greptile.com/api/retrigger?id=29444483)</sub>

> Greptile also left **1 inline comment** on this PR.

### CODE REVIEW

File: backend/pkg/libarcane/swarm/stack_deploy_engine.go [hunk 1]
```diff
@@ -1155,6 +1155,14 @@ func valueOrZero(value *uint64) uint64 {
 	return *value
 }
 
+func stringOrDefaultInternal(value, defaultValue string) string {
```
Comment (kmendell) [inline backend/pkg/libarcane/swarm/stack_deploy_engine.go]: We should move this to pkg/utils/string_util.go and then export it as other places may use this in the future

**Review by kmendell — APPROVED** [review]
