### PR TITLE
fix: lazy load project file contents on demand

### LINKED ISSUE #2257: 🐞 Bug: Project details endpoint returns huge payloads and is requested repeatedly
### Bug Description

Hey @kmendell - just flagging this as a pretty serious bug that requires urgent attention. Added in v1.17.0 or later I believe as I've not had this issue until the update. Projects are unusuable in my setup as is. Most of the issue copy below the line is LLM-gen here, but it should be pretty succinct and self-explanatory. 

These might be better off split into two separate issues, but as they've appeared together and are immediately obvious in the logs, I've filed them as one. 

You appear to be returning not just the `docker-compose.yaml` and `.env` files in the project page response, but seemingly recursively scanned project files below 1 MB in size as well, set by `PROJECT_SCAN_MAX_DEPTH` (though changing this doesn't seem to fix this). I've had some 200MB responses opening project folders. 

---

Project detail requests can return extremely large payloads and the frontend appears to request those same project details repeatedly. This causes some project pages to take seconds to minutes to load, and in some cases the browser appears to show a white page while waiting.

From tracing the local source, `GetProjectDetails()` includes `DirectoryFiles` by recursively scanning the project directory and embedding full file contents into the response. This seems to have been introduced in `v1.17.0`.

In addition, the frontend appears to repeatedly fetch:
- `/api/environments/:id/settings`
- `/api/environments/:id/projects`
- `/api/environments/:id/projects/:projectId`

This amplifies the impact of the oversized project detail payloads.

### Steps To Reproduce

1. Run Arcane against a projects directory that contains multiple compose stacks.
2. Ensure at least one project directory contains nested runtime/config files such as `data`, `db`, `logs`, `cache`, `backups`, or other text-heavy folders under the same project tree.
3. Open the `Projects` page.
4. Open one of the larger project detail pages.
5. Observe that the page may take a very long time to load or appears blank while waiting.
6. Check Arcane logs and observe very large `response.length` values for:
   - `/api/environments/0/projects/:projectId`
7. Optionally open the `Containers` page and click through containers. Observe repeated project/settings requests in the logs.

### Expected Behavior

Project detail pages should load promptly and the project details endpoint should return a reasonably sized payload.

The frontend should avoid repeatedly requesting the same project details and settings for a single interaction.

### Actual Behavior

Some project detail requests return multi-megabyte to hundred-megabyte payloads, for example:

- `response.length=12779223`
- `response.length=12949458`
- `response.length=78513258`
- `response.length=107173712`
- `response.length=216013098`

Latency scales with payload size, ranging from around 1 second to multiple minutes. The same large project IDs are also requested repeatedly.

### Screenshots

_No response_

### Arcane Version

v1.17.1

### Installation Method

Docker Compose (Recommended)

### Environment Type

Local Docker (Single instance)

### Database Type

SQLite (Default)

### Operating System

Linux

### Docker Version

20.10.3

### Browser & Version

Firefox most recent (but probably not relevant)

### Relevant Logs or Error Messages

```shell
Apr 07 07:28:45.536 INF Incoming request request.path=/api/environments/0/projects/3ffa9e43-5874-4dd9-a9b7-5759f9d38036 response.latency=1.028729376s response.status=200 response.length=12779223

Apr 07 07:12:13.915 INF Incoming request request.path=/api/environments/0/projects/cf5bd4da-8cc5-40ab-8cbc-1040d4e8d756 response.latency=2m32.403106306s response.status=200 response.length=12949458

Apr 07 07:12:13.930 INF Incoming request request.path=/api/environments/0/projects/cf5bd4da-8cc5-40ab-8cbc-1040d4e8d756 response.latency=5m6.126792194s response.status=200 response.length=12949458

Apr 07 07:11:30.595 INF Incoming request request.path=/api/environments/0/projects/d197f747-2990-4cf0-b777-cda703ba5416 response.latency=4m46.533864886s response.status=200 response.length=216013098

Apr 07 07:11:32.993 INF Incoming request request.path=/api/environments/0/projects/b4241b72-aef7-44fa-a617-86861ad1c079 response.latency=3m11.162531876s response.status=200 response.length=78513258


Comparison with small endpoints from the same logs:


Apr 07 07:28:42.567 INF Incoming request request.path=/api/environments/0/projects/counts response.latency=41.054058ms response.status=200 response.length=169

Apr 07 07:28:42.654 INF Incoming request request.path=/api/environments/0/projects response.latency=127.340948ms response.status=200 response.length=15404


Repeated request pattern from one captured window:


/api/environments/0/projects                   called 38 times
/api/environments/0/templates/variables       called 32 times
/api/environments/0/settings                  called 30 times
/api/environments/0/projects/counts           called 25 times

Project details fetched repeatedly:
- 3ffa9e43-5874-4dd9-a9b7-5759f9d38036  8 times
- cf5bd4da-8cc5-40ab-8cbc-1040d4e8d756  8 times
- 7c7db0f4-fc67-4a4d-ae6c-0ba8d4dbe70f  7 times
- c1019a52-a805-4c40-b630-557993cd0a6a  6 times
- 38361e42-a159-477d-b542-7f379b7a265f  6 times
```

### Docker Compose Configuration

```yaml
services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:latest
    container_name: arcane
    restart: unless-stopped
    ports:
      - "3552:3552"
    environment:
      - APP_URL=http://<NAS-IP>:3552
      - PUID=1026
      - PGID=100
      - ENCRYPTION_KEY=<redacted>
      - JWT_SECRET=<redacted>
      - PROJECTS_DIRECTORY=/volume1/docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /volume1/docker:/volume1/docker
```

### Environment Configuration (.env file)

```shell

```

### Additional Context

@kmendell - this is a bit too serious for me to think about fixing so I'll leave it with you. If you've introduced directory scanning depth vars (`PROJECT_SCAN_MAX_DEPTH`) that users should add, perhaps a sensible default ie `1` to avoid these huge payloads? 

Setting `PROJECT_SCAN_MAX_DEPTH=1` did not resolve the issue; I'm still getting a 13MB payload for the Arcane project. 

From local source tracing:

- `backend/internal/services/project_service.go`
  - `GetProjectDetails()` unconditionally calls:
    - `enrichWithIncludeFiles(...)`
    - `enrichWithDirectoryFiles(...)`

- `backend/pkg/projects/fs_util.go`
  - `ReadProjectDirectoryFiles(...)` recursively scans the project directory
  - it includes full text file content in `DirectoryFiles`
  - it skips only a limited set of directories
  - it includes non-binary files up to `1 MB` each

This appears to be the direct cause of the huge payloads for projects whose directories contain runtime/config data under the same tree as the compose file.

Relevant history from local git:

- `67b69376 feat: Git Sync Folder Implementation (#1629)`
  - appears to introduce directory file enrichment on project details
  - contained in `v1.17.0`

- `1174e527 perf: add depth limit and skip list to project directory scanning (#2254)`
  - mitigation via `PROJECT_SCAN_MAX_DEPTH` and `PROJECT_SCAN_SKIP_DIRS`

Likely improvements:

- return only directory file metadata initially
- fetch directory file content on demand
- avoid repeated frontend requests for the same project details/settings
- expand default skip directories to include common runtime folders such as `data`, `db`, `logs`, `cache`, `tmp`, `backup`, `backups`

### PR DESCRIPTION
**Pull request by jt196**
Return include and directory files as metadata in project details and fetch file contents only when selected in the UI. This keeps project pages fast and avoids shipping large file trees in the initial response.

Also expose the detected compose filename so the UI shows `docker-compose.yml` / `compose.yml` variants correctly.

Fixes #2257

## Checklist

- [x] This PR is **not** opened from my fork’s `main` branch

## What This PR Implements

This changes the project details flow so the initial `/projects/:projectId` response no longer embeds file contents for include files and scanned directory files. Instead, the project page receives metadata for those files and fetches content lazily only when a user selects a file in the UI.

This keeps the existing tree/classic project file UX intact while removing the large eager payloads that made some project pages extremely slow or effectively unusable.

Fixes: #2257

## Changes Made

- Return `includeFiles` and `directoryFiles` as metadata-only in the main project details payload, instead of embedding file contents eagerly.
- Add a new project file endpoint to fetch a single file by `relativePath` on demand.
- Update the project page to lazy-load include and directory file contents when selected in tree view or classic include tabs.
- Preserve already loaded include file content across refresh/save flows so editors do not blank out after reloading project details.
- Expose the detected compose filename in project details and update the UI to label the compose editor/tree item with the actual filename.

## Testing Done

- [ ] Development environment started: `./scripts/development/dev.sh start`
- [ ] Frontend verified at http://localhost:3000
- [ ] Backend verified at http://localhost:3552
- [x] Manual testing completed (describe):
  - Verified that previously heavy project pages now load normally.
  - Confirmed the main project details request dropped from multi-MB payloads to a small response (`response.length=4537` in `arcane.log` for a previously problematic project).
  - Confirmed file contents are now fetched through `/api/environments/:id/projects/:projectId/file?relativePath=...` only when files are clicked.
  - Verified lazy-loaded files such as `arcane.log`, `arcane_project_payload_issue.md`, and `arcane_bug_report_filled.md` load successfully after selection.
  - Verified the compose file label now reflects the detected compose filename rather than always showing `compose.yaml`.
- [ ] No linting errors (e.g., `just lint all`)
- [ ] Backend tests pass: `just test backend`

## AI Tool Used (if applicable)

AI Tool: Codex
Assistance Level: Moderate
What AI helped with:
- Tracing the oversized project payloads through the backend/frontend code paths.
- Drafting and implementing the metadata-only + lazy-load approach.
- Drafting issue and PR text.
I reviewed and edited all AI-generated output: Yes
I ran all required tests and manually verified changes: I manually verified the behavior on a running NAS deployment. I was not able to run the repo’s full local test/lint workflow in this environment.

## Additional Context

Before this change, affected project detail responses on my instance could reach tens to hundreds of MB because include/directory file contents were embedded in the main project payload. After this change, the main project details response is small and file contents are fetched only when explicitly opened.

**Disclaimer** Greptiles Reviews use AI, make sure to check over its work.

To better help train Greptile on our codebase, if the comment is useful and valid **Like** the comment, if its not helpful or invalid **Dislike**

To have Greptile Re-Review the changes, mention `greptileai`.

<details open><summary><h3>Greptile Summary</h3></summary>

This PR implements a lazy-load strategy for project file contents: the main project details endpoint now returns metadata-only for `includeFiles` and `directoryFiles`, and a new `/file?relativePath=...` endpoint serves individual file contents on demand. It also exposes the detected compose filename so the UI can show `docker-compose.yml` / `compose.yml` variants.

- The classic view's desktop `ResizableSplit` still hardcodes `title=\"compose.yaml\"` (line 1186 of `+page.svelte`); every other `CodePanel` in the same file was updated to use `{composeFileName}`, making this the only stale instance.
</details>

<details open><summary><h3>Confidence Score: 4/5</h3></summary>

Mostly safe to merge; one missed label update causes the wrong compose filename to display in the classic desktop layout.

One P1 finding: the classic/desktop CodePanel still hardcodes 'compose.yaml' while every other instance was updated — directly contradicts a stated goal of this PR. All other findings are P2 style notes. Fixing the hardcoded title is a one-line change.

frontend/src/routes/(app)/projects/[projectId]/+page.svelte — hardcoded compose filename in classic desktop split
</details>

<details open><summary><h3>Vulnerabilities</h3></summary>

No significant security concerns. The new `/file` endpoint correctly requires BearerAuth or ApiKeyAuth, guards against path traversal via `IsSafeSubdirectory`, blocks symlink access with `os.Lstat` + mode check, and rejects binary files. Include files may legitimately resolve outside the project directory (Docker Compose spec); the code documents and accounts for this. No secrets are leaked in error responses from the handler.
</details>

<a href="https://app.greptile.com/ide/codex?prompt=Fix%20the%20following%202%20code%20review%20issues.%20Work%20through%20them%20one%20at%20a%20time%2C%20proposing%20concise%20fixes.%0A%0A---%0A%0A%23%23%23%20Issue%201%20of%202%0Afrontend%2Fsrc%2Froutes%2F%28app%29%2Fprojects%2F%5BprojectId%5D%2F%2Bpage.svelte%3A1186%0A**Hardcoded%20filename%20missed%20in%20classic%2Fdesktop%20split**%0A%0AThe%20PR%20updates%20the%20compose%20label%20to%20use%20the%20detected%20%60composeFileName%60%20in%20the%20tree%20view%20and%20the%20classic%20tablet%20layout%2C%20but%20the%20classic%20view's%20desktop%20%60ResizableSplit%60%20first%20panel%20still%20hardcodes%20%60%22compose.yaml%22%60.%20Projects%20using%20%60docker-compose.yml%60%20%28or%20any%20other%20variant%29%20will%20show%20the%20wrong%20title%20here.%0A%0A%60%60%60suggestion%0A%09%09%09%09%09%09%09%09%09%09%09%09title%3D%7BcomposeFileName%7D%0A%60%60%60%0A%0A%23%23%23%20Issue%202%20of%202%0Abackend%2Finternal%2Fservices%2Fproject_service.go%3A736-741%0A**No%20file%20size%20guard%20before%20%60os.ReadFile%60**%0A%0AThe%20directory-scan%20path%20in%20%60enrichWithDirectoryFiles%60%20skips%20files%20larger%20than%201%20MB%20%28%60info.Size%28%29%20%3E%201024*1024%60%29%2C%20but%20%60GetProjectFileContent%60%20reads%20the%20file%20into%20memory%20with%20no%20size%20limit.%20An%20authenticated%20user%20%28or%20the%20frontend%29%20could%20request%20a%20large%20project%20file%20%E2%80%94%20e.g.%20a%20log%20or%20archive%20that%20sits%20in%20the%20project%20directory%20%E2%80%94%20and%20cause%20high%20memory%20use%20per%20request.%20Adding%20a%20size%20check%20here%20mirrors%20the%20existing%20guard%20and%20keeps%20memory%20usage%20bounded.%0A%0A%60%60%60go%0Aif%20info.Size%28%29%20%3E%201024*1024%20%7B%0A%20%20%20%20return%20project.IncludeFile%7B%7D%2C%20%26common.ProjectFileBadRequestError%7B%0A%20%20%20%20%20%20%20%20Err%3A%20fmt.Errorf%28%22file%20too%20large%20%28max%201%20MB%29%22%29%2C%0A%20%20%20%20%7D%0A%7D%0A%60%60%60%0A%0A&repo=getarcaneapp%2Farcane">Fix All in Codex</a>

<details><summary>Prompt To Fix All With AI</summary>

`````markdown
This is a comment left during a code review.
Path: frontend/src/routes/(app)/projects/[projectId]/+page.svelte
Line: 1186

Comment:
**Hardcoded filename missed in classic/desktop split**

The PR updates the compose label to use the detected `composeFileName` in the tree view and the classic tablet layout, but the classic view's desktop `ResizableSplit` first panel still hardcodes `"compose.yaml"`. Projects using `docker-compose.yml` (or any other variant) will show the wrong title here.

```suggestion
												title={composeFileName}
```

How can I resolve this? If you propose a fix, please make it concise.

---

This is a comment left during a code review.
Path: backend/internal/services/project_service.go
Line: 736-741

Comment:
**No file size guard before `os.ReadFile`**

The directory-scan path in `enrichWithDirectoryFiles` skips files larger than 1 MB (`info.Size() > 1024*1024`), but `GetProjectFileContent` reads the file into memory with no size limit. An authenticated user (or the frontend) could request a large project file — e.g. a log or archive that sits in the project directory — and cause high memory use per request. Adding a size check here mirrors the existing guard and keeps memory usage bounded.

```go
if info.Size() > 1024*1024 {
    return project.IncludeFile{}, &common.ProjectFileBadRequestError{
        Err: fmt.Errorf("file too large (max 1 MB)"),
    }
}
```

How can I resolve this? If you propose a fix, please make it concise.
`````

</details>

<sub>Reviews (2): Last reviewed commit: ["refactor: use await blocks for lazy proj..."](https://github.com/getarcaneapp/arcane/commit/c163265a15b737c7e3ec2680efcb741fb1499aa1) | [Re-trigger Greptile](https://app.greptile.com/api/retrigger?id=27568589)</sub>

### CODE REVIEW

**Comment by kmendell** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scan Engine |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/kmendell-XqXhZ889F7MYCfD6CFnDWH/pr-checks/198e9ab4-0b3e-49cb-9d4e-144fa1137895?refs=8ab45a8c5053d1aa8ce33b073330936be9093935&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

**Comment by jt196** [comment]
The remaining failing check appears unrelated to this PR.

`Go Tests (backend)` is failing in the `Setup Just` step before tests start:
`extractions/setup-just@v3` -> `Cannot read properties of undefined (reading 'headers')`

The other checks are passing, so this looks like a CI/action issue rather than a regression from the changes here.

File: backend/internal/services/project_service.go [hunk 1]
```diff
@@ -50,6 +50,12 @@ type ProjectService struct {
 	composeNameToProjID map[string]string
 }
 
+var (
+	ErrProjectFileBadRequest = errors.New("invalid project file request")
```
Comment (kmendell) [inline backend/internal/services/project_service.go]: Move these to common/errors.go and follow how other others are defined.

File: backend/internal/services/project_service.go [hunk 2]
```diff
@@ -674,6 +681,85 @@ func (s *ProjectService) GetProjectDetails(ctx context.Context, projectID string
...
+		}
+		return project.IncludeFile{}, fmt.Errorf("failed to stat file: %w", err)
+	}
+	if info.IsDir() {
+		return project.IncludeFile{}, fmt.Errorf("%w: path refers to a directory", ErrProjectFileBadRequest)
+	}
+	if info.Mode()&os.ModeSymlink != 0 {
+		return project.IncludeFile{}, fmt.Errorf("%w: symlink files are not supported", ErrProjectFileForbidden)
+	}
+	if info.Size() > 1024*1024 {
```
Comment (kmendell) [inline backend/internal/services/project_service.go]: I wouldn't restrict file sizes, cause if ive learned anything, is there not one way to do stuff, and Im sure there is someone out there that's has a file bigger than this.

File: backend/pkg/projects/fs_util.go [hunk 3]
```diff
@@ -227,6 +240,10 @@ func isBinaryProjectFileContentInternal(content []byte) bool {
 	return slices.Contains(content[:checkSize], 0)
 }
 
+func IsBinaryProjectFileContent(content []byte) bool {
```
Comment (kmendell) [inline backend/pkg/projects/fs_util.go]: Just make the other function a exported one and rmeove the internal suffix, and remove the stub

File: backend/pkg/projects/includes.go [hunk 4]
```diff
@@ -33,9 +33,19 @@ type IncludeFile struct {
 	Content      string `json:"content"`
 }
 
+// ParseIncludesMetadata reads a compose file and extracts include directives without
+// embedding include file content in the returned payload.
+func ParseIncludesMetadata(composeFilePath string, envMap EnvMap) ([]IncludeFile, error) {
```
Comment (kmendell) [inline backend/pkg/projects/includes.go]: Same

File: backend/pkg/projects/includes.go [hunk 5]
```diff
@@ -33,9 +33,19 @@ type IncludeFile struct {
...
+	return parseIncludesInternal(composeFilePath, envMap, false)
+}
+
 // ParseIncludes reads a compose file and extracts all include directives.
 // envMap is used to expand variables (e.g., ${VAR}) in include paths.
 func ParseIncludes(composeFilePath string, envMap EnvMap) ([]IncludeFile, error) {
+	return parseIncludesInternal(composeFilePath, envMap, true)
```
Comment (kmendell) [inline backend/pkg/projects/includes.go]: same.

File: backend/pkg/projects/includes.go [hunk 6]
```diff
@@ -100,17 +110,19 @@ func parseIncludeItemInternal(item any, baseDir string, envMap EnvMap) (IncludeF
 	}
 	fullPath = filepath.Clean(fullPath)
 
-	var content string
-	fileContent, err := os.ReadFile(fullPath)
-	if err != nil {
-		if errors.Is(err, os.ErrNotExist) {
-			// File doesn't exist yet - return empty content so it can be created
-			content = "# This file will be created when you save changes\nservices:\n"
+	content := ""
```
Comment (kmendell) [inline backend/pkg/projects/includes.go]: I would revert this line, I find it easier to understand when using the var sytax as its "Define now assign later"

**Review by kmendell — CHANGES_REQUESTED** [review]
Start with this then ill review more. That being said, Alot of this may be able to be avoided just be using sveltes {#await} block.

File: backend/internal/services/project_service.go (hunk 1 above)
Comment (jt196) [reply backend/internal/services/project_service.go]: Done. 

Updated this to follow the existing common error pattern instead of package-local sentinels:
- moved the project file request errors into `backend/internal/common/errors.go`
- used `Err error` on the new error structs to match the surrounding style
- handler now maps them with `errors.As(...)`

File: backend/internal/services/project_service.go (hunk 2 above)
Comment (jt196) [reply backend/internal/services/project_service.go]: Removed.

File: backend/pkg/projects/fs_util.go (hunk 3 above)
Comment (jt196) [reply backend/pkg/projects/fs_util.go]: Adjusted this to export the existing helper directly and removed the extra wrapper/internal suffix version.

File: backend/pkg/projects/includes.go (hunk 4 above)
Comment (jt196) [reply backend/pkg/projects/includes.go]: Removed.

File: backend/pkg/projects/includes.go (hunk 5 above)
Comment (jt196) [reply backend/pkg/projects/includes.go]: Removed. 

exposed a single `ParseIncludes(..., includeContent bool)` function and updated the two call sites accordingly

File: backend/pkg/projects/includes.go (hunk 6 above)
Comment (jt196) [reply backend/pkg/projects/includes.go]: Done.

**Comment by jt196** [comment]
> Start with this then ill review more. That being said, Alot of this may be able to be avoided just be using sveltes {#await} block.

So... the issue was the huge payloads - 10-200MB. Await can help manage async data retrieval and loading into the frontend, but it doesn't resolve all the issues working with large amounts of data. 

Fetching on selection keeps things nice and streamlined and only loads the files when the user requests their contents. 

@kmendell - I rarely need this kind of thing, I'm only looking at compose and .env files most of the time. I assume the majority of users don't want the cost of this transaction on every project load.

File: frontend/src/routes/(app)/projects/[projectId]/+page.svelte [hunk 7]
```diff
@@ -891,29 +1060,53 @@
...
-														language="yaml"
-														bind:value={includeFilesState[includeFile.relativePath]}
-														bind:hasErrors={includeFilesHasErrors[includeFile.relativePath]}
-														bind:validationReady={includeFilesValidationReady[includeFile.relativePath]}
-														fileId={`project:${projectId}:include:${includeFile.relativePath}`}
-														originalValue={originalIncludeFiles[includeFile.relativePath]}
-														enableDiff={true}
-														editorContext={codeEditorContext}
-													/>
+													{@const isLoadingIncludeFile = isProjectFileLoading('include', includeFile.relativePath)}
```
Comment (kmendell) [inline frontend/src/routes/(app)/projects/[projectId]/+page.svelte]: This is a outline, but this is how sveltes await block works. Could also somehow put this in a [Snippet](https://svelte.dev/docs/svelte/snippet), to reduce the duplciated code logic. ---  Instead of:

```svelte
{@const isLoadingIncludeFile = isProjectFileLoading('include', includeFile.relativePath)}
{@const includeFileError = getProjectFileError('include', includeFile.relativePath)}
{#if isLoadingIncludeFile}
    <div>{m.common_loading()}</div>
{:else if includeFileError}
    <div>{includeFileError}</div>
{:else}
    <CodePanel ... />
{/if}

```

Refactor `ensureProjectFileContentLoaded` to return the loaded file, then use:

```svelte
{#await ensureProjectFileContentLoaded('include', includeFile.relativePath)}
    <div>{m.common_loading()}</div>
{:then loadedFile}
    <CodePanel value={loadedFile.content} ... />
{:catch error}
    <div>{error.message}</div>
{/await}

```

This eliminates `projectFileLoading`, `projectFileErrors`, and the related helper functions, letting Svelte handle the promise states natively.

Comment (jt196) [reply frontend/src/routes/(app)/projects/[projectId]/+page.svelte]: OK Gotcha... completely misunderstood you! Just testing this.

Comment (jt196) [reply frontend/src/routes/(app)/projects/[projectId]/+page.svelte]: OK @kmendell - that await refactor has been done and working in my docker environment.
