### PR TITLE
feat: self update digest tracking and fixes

### LINKED ISSUE #884: 🐞 Bug: Self-update doesn't update
### Bug Description

At some point arcane self-upgrade feature was introduced. Clicking on the new version available button pulls in the new image, but only restarts the old one, instead of the new one.

### Steps To Reproduce

See description

### Expected Behavior

Self-upgrade actually starts the new version

### Actual Behavior

The same old arcane version is started

### Screenshots

_No response_

### Arcane Version

v1.8.1

### Operating System

Linux

### Browser

N/A

### Docker Version

28.5.1

### Additional Context

_No response_

### LINKED ISSUE #908: 🐞 Bug: Update Arcane-agent
### Bug Description

The Update to Latest Version button links to the old image address, which is no longer valid, causing it to crash with an error.
The documentation page lists a different image address.

Image
Image
Image

### Steps To Reproduce

Go to the Environments tab, select the agent, and click to update it to the latest version.

### Expected Behavior

The agent will be updated to the latest version, restarted, and begin working.

### Actual Behavior

Update error due to incorrect address

### Screenshots

_No response_

### Arcane Version

1.8.1

### Operating System

Windows

### Browser

Chrome

### Docker Version

29.0.0

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by cabaucom376**
First two commits are an attempt to close #908 and close #884

Fixes: https://github.com/getarcaneapp/arcane/issues/981

The rest is an attempt at a digest based tag tracking, so if you run the `next` image you should theoretically be able to self update when theres a new next image available. Revert if not desired, if okay with the idea I can refine.

**Disclaimer** Greptiles Reviews uses AI, make sure to check over its work

<h2>Greptile Overview</h2>

<details><summary><h3>Greptile Summary</h3></summary>

This PR addresses three critical self-update bugs (#908, #884, #981) and introduces digest-based update tracking for non-semver tags like `next`.

## Key Changes

- **Fixed image references**: Updated all hardcoded image paths from `ofkm/arcane` to `ghcr.io/getarcaneapp/arcane`, resolving broken update links
- **Explicit image pull**: Added image pull before spawning upgrader container to ensure the latest version exists locally, fixing false-success updates
- **Digest tracking**: Implemented registry manifest checking to detect updates for non-semver tags by comparing image digests
- **Rebranding**: Updated labels, module paths, and URLs from `ofkm` to `getarcaneapp` organization

## Implementation

The digest tracking works by:
1. Detecting current container's tag and digest from Docker inspect + `/proc/self/cgroup`
2. Querying the registry API (`HEAD /v2/{repo}/manifests/{tag}`) to get latest digest
3. Comparing current vs latest digest to determine if update is available
4. Supporting both anonymous and authenticated registry access

## Issues Found

- **Tailwind CSS**: `bg-linear-to-br` is invalid (should be `bg-gradient-to-br`) on lines 164 and 188 of `sidebar-updatebanner.svelte`
- **Platform dependency**: Container detection relies on Linux-specific `/proc/self/cgroup`, won't work on Windows containers or other platforms

## Testing Recommendations

- Check that digest updates work correctly for `next` tag with private registries
- Verify self-update works from v1.7.2 → v1.9.0 (issue #981 scenario)
- Ensure upgrade from different registry configurations (Docker Hub, GHCR, custom registries)

</details>
<details><summary><h3>Confidence Score: 4/5</h3></summary>

- This PR is safe to merge with minor CSS fixes needed
- The core logic for fixing self-update bugs is sound and properly addresses the reported issues. The digest tracking implementation follows best practices with proper authentication, caching, and error handling. However, two Tailwind CSS class names are invalid and need correction, and there's a Linux-specific dependency that may limit portability. These are non-critical issues that don't affect core functionality.
- `frontend/src/lib/components/sidebar/sidebar-updatebanner.svelte` needs CSS class fixes on lines 164 and 188 (change `bg-linear-to-br` to `bg-gradient-to-br`)
</details>

<details><summary><h3>Important Files Changed</h3></summary>

File Analysis

| Filename | Score | Overview |
|----------|-------|----------|
| backend/internal/services/version_service.go | 4/5 | Added digest-based update tracking for non-semver tags (e.g., `next`). Detects container info from `/proc/self/cgroup` and compares registry digests. Implementation is solid but relies on Linux-specific detection. |
| backend/internal/services/container_registry_service.go | 4/5 | Added `GetImageDigest` to fetch manifests from registries with authentication support. Uses case-insensitive header matching and caching. Well-structured with proper error handling. |
| backend/internal/services/system_upgrade_service.go | 5/5 | Fixed image reference from `ofkm/arcane` to `ghcr.io/getarcaneapp/arcane` and added explicit image pull before spawning upgrader container. Addresses issue #908 and #981. |
| backend/internal/cli/upgrade/upgrade.go | 5/5 | Updated hardcoded image references from `ghcr.io/ofkm/arcane` to `ghcr.io/getarcaneapp/arcane`. Simple string replacement change. |
| frontend/src/lib/components/sidebar/sidebar-updatebanner.svelte | 3/5 | Added digest-based update display for non-semver tags. Shows shortened digest (first 12 chars) for tracking updates. Has a previously reported CSS class issue (`bg-linear-to-br` is invalid). |
| backend/internal/dto/version_dto.go | 5/5 | Added `currentTag`, `currentDigest`, and `newestDigest` fields to support digest-based tracking. Clean schema extension. |

</details>

</details>

### CODE REVIEW

**Comment by kmendell** [comment]
I think the regsitry service is all duplicate logic from the container_registry service.

File: backend/internal/services/system_upgrade_service.go [hunk 1]
```diff
@@ -85,24 +85,29 @@ func (s *SystemUpgradeService) TriggerUpgradeViaCLI(ctx context.Context, user mo
...
+		"currentTag":    currentImageTag,
 		"method":        "cli",
 	}
 	if err := s.eventService.LogUserEvent(ctx, models.EventTypeSystemUpgrade, user.ID, user.Username, metadata); err != nil {
 		slog.Warn("Failed to log upgrade event", "error", err)
 	}
 
-	// Use the official Arcane image for the upgrader container
-	// This ensures we always use the packaged CLI from the official image
-	upgraderImage := "ghcr.io/ofkm/arcane:latest"
```
Comment (kmendell) [inline backend/internal/services/system_upgrade_service.go:101]: this just pulls a another image just to use the cli tool it can be pinned to latest its not the end of the world this isn't used for anything but the CLI upgrade it self.

**Comment by cabaucom376** [comment]
@greptileai

**Comment by cabaucom376** [comment]
I have no clue how to actually test if this works lol

**Comment by kmendell** [comment]
On the sidebar manually set the debug={true} that should make the update banner to show up

**Comment by kmendell** [comment]
@greptileai

**Comment by kmendell** [comment]
@greptileai

**Review by kmendell — APPROVED** [review]
