### PR TITLE
fix: Update Projects button only updates project containers

### LINKED ISSUE #2288: 🐞 Bug: Update Projects not behaving as expected (is updating ALL containers)
### Bug Description

On the projects page there is a button on the top right that is named "Update Projects". I would expect only project related containers to be updated. Instead it is updating ALL containers.

I am in the process of moving Portainer Stacks to Arcane Projects. I had added only one project to Arcane. All other containers where visible but not yet defined in Arcane. When I clicked on "Update Projects" it started, without any warning, to update ALL containers running on that docker instance. I expected it to only update the containers related to that one project.

### Steps To Reproduce

1. Go to Projects Tab
2. Click on "Update Projects"

### Expected Behavior

I expected "Update Projects" to only update the containers related to the projects and redeploy the project.

### Actual Behavior

ALL containers are updated. No warning given.

### Screenshots

_No response_

### Arcane Version

v1.17.2

### Installation Method

Docker Compose (Recommended)

### Environment Type

Local Docker (Single instance)

### Database Type

SQLite (Default)

### Operating System

Linux

### Docker Version

29.4.0

### Browser & Version

Firefox 149.0

### Relevant Logs or Error Messages

```shell

```

### Docker Compose Configuration

```yaml

```

### Environment Configuration (.env file)

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GiulioSavini**
## Summary
- The "Update Projects" button on the Projects page was calling the general auto-updater endpoint (`/updater/run`), which updated **ALL** containers on the Docker instance
- Changed to iterate through defined projects and pull images + deploy each one individually using `projectService.pullProjectImages()` and `projectService.deployProject()`
- Removed unused `imageService` import

## Test plan
- [ ] Navigate to the Projects page with some projects defined and other non-project containers running
- [ ] Click "Update Projects"
- [ ] Verify only project containers are updated, not all containers
- [ ] Verify toast notification shows on success/failure

Fixes #2288

**Disclaimer** Greptiles Reviews use AI, make sure to check over its work.

To better help train Greptile on our codebase, if the comment is useful and valid **Like** the comment, if its not helpful or invalid **Dislike**

To have Greptile Re-Review the changes, mention `greptileai`.

<details open><summary><h3>Greptile Summary</h3></summary>

This PR replaces the broad `/updater/run` call with a targeted update flow: it first checks all images for available updates, identifies which projects are affected, then redeploys only those projects in parallel using `Promise.allSettled`. This correctly scopes the "Update Projects" action to project containers only and addresses the earlier review concerns around partial pagination and mid-loop failure.
</details>

<details open><summary><h3>Confidence Score: 5/5</h3></summary>

Safe to merge — the core fix is correct and previous review concerns are addressed; the one remaining finding is a minor i18n style issue.

All remaining findings are P2 (style/best practice). The logic is sound: parallel updates via Promise.allSettled, explicit project filtering, and a 'nothing to update' early-exit path all improve over the original. Previous concerns about pagination and error propagation are resolved.

No files require special attention.
</details>

<a href="https://chatgpt.com/codex/deeplink?prompt=IMPORTANT%3A%20Work%20in%20the%20repository%20%22getarcaneapp%2Farcane%22%20on%20the%20existing%20branch%20%22fix%2Fupdate-projects-scope%22.%20Checkout%20that%20branch%20%E2%80%94%20do%20NOT%20create%20a%20new%20branch%20or%20open%20a%20new%20PR.%20Push%20your%20changes%20to%20%22fix%2Fupdate-projects-scope%22.%0A%0AFix%20the%20following%201%20code%20review%20issues.%20Work%20through%20them%20one%20at%20a%20time%2C%20proposing%20concise%20fixes.%0A%0A---%0A%0A%23%23%23%20Issue%201%20of%201%0Afrontend%2Fsrc%2Froutes%2F%28app%29%2Fprojects%2F%2Bpage.svelte%3A80%0A**Hardcoded%20English%20string%20bypasses%20i18n**%0A%0AThis%20error%20message%20is%20displayed%20directly%20to%20the%20user%20via%20%60error.message%60%20in%20the%20%60onError%60%20handler%20%28line%2094%29%2C%20but%20it's%20a%20raw%20English%20string%20rather%20than%20a%20localised%20message%20key.%20Other%20error%2Fsuccess%20toasts%20on%20this%20page%20all%20go%20through%20%60m.*%60%20message%20functions.%0A%0AIf%20a%20dedicated%20message%20key%20doesn't%20exist%20yet%2C%20a%20fallback%20approach%20is%20to%20keep%20the%20English%20template%20but%20replace%20the%20raw%20%60error.message%60%20in%20%60onError%60%20with%20a%20composed%20i18n%20string%20that%20injects%20the%20counts.%0A%0A"><picture><source media="(prefers-color-scheme: dark)" srcset="https://greptile-static-assets.s3.amazonaws.com/badges/FixAllInCodexDark.svg?v=2"><source media="(prefers-color-scheme: light)" srcset="https://greptile-static-assets.s3.amazonaws.com/badges/FixAllInCodex.svg?v=2">Fix All in Codex</picture></a>

<details><summary>Prompt To Fix All With AI</summary>

`````markdown
This is a comment left during a code review.
Path: frontend/src/routes/(app)/projects/+page.svelte
Line: 80

Comment:
**Hardcoded English string bypasses i18n**

This error message is displayed directly to the user via `error.message` in the `onError` handler (line 94), but it's a raw English string rather than a localised message key. Other error/success toasts on this page all go through `m.*` message functions.

If a dedicated message key doesn't exist yet, a fallback approach is to keep the English template but replace the raw `error.message` in `onError` with a composed i18n string that injects the counts.

How can I resolve this? If you propose a fix, please make it concise.
`````

</details>

<sub>Reviews (2): Last reviewed commit: ["fix: only redeploy projects that actuall..."](https://github.com/getarcaneapp/arcane/commit/9e29955883d559793d5f757b53bd0f7705bca158) | [Re-trigger Greptile](https://app.greptile.com/api/retrigger?id=27830145)</sub>

### CODE REVIEW

**Comment by kmendell** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scan Engine |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/kmendell-XqXhZ889F7MYCfD6CFnDWH/pr-checks/c0b345db-49f2-4fb2-8104-27a165cf9cca?refs=33552908372f2d341107421a12d477a84bbcc00d&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

File: frontend/src/routes/(app)/projects/+page.svelte [hunk 1]
```diff
@@ -41,13 +40,28 @@
 
 	const checkUpdatesMutation = createMutation(() => ({
 		mutationKey: ['projects', 'check-updates', envId],
-		mutationFn: () => imageService.runAutoUpdate(),
+		mutationFn: async () => {
+			const allProjects = await projectService.getProjectsForEnvironment(envId, { limit: 1000 });
+			const results = await Promise.allSettled(
+				allProjects.data.map(async (proj) => {
+					await projectService.pullProjectImages(proj.id);
```
Comment (kmendell) [inline frontend/src/routes/(app)/projects/+page.svelte]: This will get performed on every project then, even if there no update available for the specific image. This would cause un-needed stress on the server.

Comment (GiulioSavini) [reply frontend/src/routes/(app)/projects/+page.svelte]: Good catch — totally fair point, the previous version was basically "update everything and hope for the best" 😅

Pushed 535adf85 which flips the logic around:

1. Single `checkAllImages` call to refresh update info in one shot.
2. Walks the returned images, keeps only the ones where `updateInfo.hasUpdate === true`, and collects the project IDs from their `usedBy` map.
3. Redeploys *only* those projects with `pullPolicy: 'always'` (so the separate `pullProjectImages` call is gone too — it was double-pulling anyway).

If nothing has updates the button is essentially free: one bulk check, zero deploys, and the user gets an "Up to Date" toast instead of a fake success. Let me know if you'd rather move this logic to the backend instead, happy to refactor.

**Review by kmendell — APPROVED** [review]
